---
default_language_version:
  python: python3.10
exclude: ^$
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: debug-statements
  - repo: 'https://github.com/asottile/pyupgrade'
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        args:
          - '--py39-plus'
  - repo: 'https://github.com/PyCQA/isort'
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - '--profile'
          - black
          - '--filter-files'
  - repo: 'https://github.com/psf/black'
    rev: 22.6.0
    hooks:
      - id: black
  - repo: 'https://github.com/PyCQA/flake8'
    rev: 4.0.1
    hooks:
      - id: flake8
        entry: pflake8
        additional_dependencies:
          - flake8-docstrings
          - pydocstyle
          - pycodestyle
          - flake8-comprehensions
          - flake8-noqa
          - mccabe
          - pyproject-flake8
  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: v0.961
    hooks:
      - id: mypy
        types:
          - python
        additional_dependencies:
          - types-requests
          - pydantic
  - repo: 'https://github.com/Lucas-C/pre-commit-hooks-nodejs'
    rev: v1.1.2
    hooks:
      - id: markdown-toc
        args:
          - '--indent'
          - '    '
          - '-i'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: check-json
        exclude: (.vscode|.devcontainer)
  - repo: 'https://github.com/adrienverge/yamllint.git'
    rev: v1.27.1
    hooks:
      - id: yamllint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        stages: [manual]
  - repo: https://github.com/jeeftor/conventional-pre-commit
    rev: v1.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
